packages:
  - 'packages/*'
  - 'examples/*'
  - 'e2e'
  - '!**/test/**'
catalog:
  '@hono/node-server': ^2.1.1
  '@tsconfig/node22': ^22.0.6
  '@types/node': ^26.4.1
  drizzle-kit: 1.0.0-rc.4
  drizzle-orm: 1.0.0-rc.4
  hono: ^4.13.5
allowBuilds:
  better-sqlite3: false
  esbuild: false
  workerd: false
minimumReleaseAgeExclude:
  - '@cloudflare/workers-types'
