name: Deploy

on:
  workflow_dispatch: {}
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
      - run: make
      - run: pnpm publish --access=public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
