name: Deploy

on:
  workflow_dispatch: {}
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"
          node-version-file: ".node-version"

      - run: make

      - run: pnpm publish -r --filter @block65/webcrypto-web-push --access=public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
